// Project content transcribed from Rashmika Rupasinghe's supplied CV.
export const portfolioProjects = [
  {
    id: 3,
    title: "PortalKit",
    description: "Performed manual, smoke, and black box testing for a client–freelancer project management system before UAT release. Wrote and executed test cases, documented bugs, and collaborated with developers to improve software quality.",
    longDescription: "PortalKit is a client–freelancer project management system. My contribution focused on software quality testing before UAT release.\n\nI performed manual, smoke, and black box testing, developed and executed test cases, documented bugs, and worked alongside the development team to enhance software quality.",
    image: "/placeholder.svg",
    images: [] as string[],
    technologies: ["Manual Testing", "Smoke Testing", "Black Box Testing", "Test Cases", "Bug Reporting"],
    category: "qa",
    liveUrl: "https://portalkit.app/",
    githubUrl: "",
    features: ["Client–freelancer project management", "Manual testing", "Smoke and black box testing", "Test case development and execution", "Bug documentation", "Collaboration with developers"],
    challenges: ["Checking system functionality before UAT release", "Identifying and documenting software defects"],
    solutions: ["Developed and performed test cases", "Documented bugs and collaborated with the development team"],
    timeline: "Before UAT release",
    client: "Business project",
    year: "Not specified in CV",
  },
  {
    id: 1,
    title: "Criclytics",
    description: "Created an interactive Power BI dashboard for cricket analytics using real-world data to explore player performance, match strategies, and trends. Improved data processing and visualization to support faster reporting and data-driven decisions.",
    longDescription: "Criclytics is a personal cricket analytics project built around an interactive Power BI dashboard using real-world data.\n\nThe dashboard provides insights into player performance, match strategies, and trends. Better data processing and visualization support faster reporting and data-driven decisions.",
    image: "/cricklytics.jpg",
    images: [] as string[],
    technologies: ["Power BI", "Data Analytics", "Data Visualization"],
    category: "analytics",
    liveUrl: "https://1drv.ms/v/c/a86c177745b40270/IQABiYBi5Z5VT6GBzY55CNkzAeJE8P73TLHqgY8DBXZmRsw?e=MLjzJI",
    githubUrl: "https://github.com/IT22106360/Criclytics",
    features: ["Interactive cricket analytics dashboard", "Real-world cricket data", "Player performance insights", "Match strategy and trend analysis"],
    challenges: ["Turning real-world cricket data into useful insights", "Supporting faster reporting and decisions"],
    solutions: ["Created an interactive Power BI dashboard", "Improved data processing and visualization"],
    timeline: "Not specified in CV",
    client: "Personal project",
    year: "Not specified in CV",
  },
  {
    id: 2,
    title: "MedIntel",
    description: "Participated in the development and validation of an AI-based antibiotic recommendation system selected as a semifinalist at IEEE EMBS Brainstorm 2025, University of Moratuwa.",
    longDescription: "MedIntel is an AI-based antibiotic recommendation system entered in Brainstorm 2025, organized by IEEE EMBS at the University of Moratuwa.\n\nI participated in its development and validation. The system was selected as a semifinalist in the competition.",
    image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=400&h=300&fit=crop",
    images: [] as string[],
    technologies: ["AI", "Healthcare", "System Validation"],
    category: "ml",
    liveUrl: "",
    githubUrl: "",
    features: ["AI-based antibiotic recommendations", "Development and validation", "IEEE EMBS Brainstorm 2025 semifinalist"],
    challenges: ["Developing an AI-based antibiotic recommendation system", "Validating the competition solution"],
    solutions: ["Participated in system development and validation", "Contributed to a solution selected as a semifinalist"],
    timeline: "Brainstorm 2025",
    client: "Competition project",
    year: "2025",
  },
  {
    id: 4,
    title: "Retention Radar",
    description: "Led a hiring analytics project for data scientists, including data cleaning, preprocessing, and handling imbalanced datasets. Built and deployed Decision Tree, Random Forest, SVM, and Logistic Regression models using Flask with a simple web interface.",
    longDescription: "Retention Radar is an academic predictive AI project in hiring analytics for data scientists. I led data cleaning and preprocessing, including work with imbalanced datasets.\n\nI built and deployed predictive models using Decision Trees, Random Forest, SVM, and Logistic Regression, with Flask and a simple web interface.",
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=300&fit=crop",
    images: [] as string[],
    technologies: ["Python", "Flask", "Predictive Modeling", "Data Preprocessing"],
    category: "ml",
    liveUrl: "",
    githubUrl: "https://github.com/IT22106360/QuantaML-FDM-Employee-Retention",
    features: ["Data cleaning and preprocessing", "Imbalanced dataset handling", "Decision Tree and Random Forest models", "SVM and Logistic Regression models", "Flask deployment", "Simple web interface"],
    challenges: ["Preparing data for predictive modeling", "Handling imbalanced datasets"],
    solutions: ["Performed data cleaning and preprocessing", "Built and deployed multiple predictive models using Flask"],
    timeline: "Not specified in CV",
    client: "Academic project",
    year: "Not specified in CV",
  },
  {
    id: 5,
    title: "Instrument Hub",
    description: "Developed a personalized e-commerce recommendation system for musical instruments using machine learning. Applied collaborative and content-based filtering to improve recommendation accuracy.",
    longDescription: "Instrument Hub is an academic AI recommendation system for musical instruments in an e-commerce setting.\n\nI developed personalized recommendations using machine learning, applying collaborative and content-based filtering to improve recommendation accuracy.",
    image: "/instrument-hub.jpg",
    images: [] as string[],
    technologies: ["Machine Learning", "Collaborative Filtering", "Content-Based Filtering"],
    category: "ml",
    liveUrl: "",
    githubUrl: "https://github.com/ascottR/Recommendation_SYS",
    features: ["Musical instrument recommendations", "Personalized e-commerce suggestions", "Collaborative filtering", "Content-based filtering"],
    challenges: ["Personalizing musical instrument recommendations", "Improving recommendation accuracy"],
    solutions: ["Applied collaborative filtering", "Applied content-based filtering"],
    timeline: "Not specified in CV",
    client: "Academic project",
    year: "Not specified in CV",
  },
]
